(() => {
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY="super_me_v1", SPORT_TYPES=["Bici","Corsa","Calisthenics","Camminata","Calcio"];
const defaults=()=>({profile:{weight:null,height:null},goals:{calories:null,sportMinutes:null,weightTarget:null,sysMax:null,diaMax:null},food:[],sport:[],pressure:[],weight:[]});
let state=load(),tab="today",mediaRecorder=null,recordChunks=[],recordStart=0,recordTimer=null,activeStream=null;
function load(){try{return {...defaults(),...(JSON.parse(localStorage.getItem(KEY))||{})}}catch{return defaults()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36), nowISO=()=>new Date().toISOString();
const isToday=iso=>new Date(iso).toDateString()===new Date().toDateString();
const fmtTime=iso=>new Intl.DateTimeFormat("it-IT",{hour:"2-digit",minute:"2-digit"}).format(new Date(iso));
const fmtDate=d=>new Intl.DateTimeFormat("it-IT",{weekday:"long",day:"numeric",month:"long"}).format(d);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const sum=(a,k)=>a.reduce((s,x)=>s+(+x[k]||0),0), latest=a=>[...a].sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt))[0], pct=(n,d)=>d?Math.max(0,Math.min(100,Math.round(n/d*100))):0;
function todayFood(){return state.food.filter(x=>isToday(x.createdAt))} function todaySport(){return state.sport.filter(x=>isToday(x.createdAt))}
function weekMinutes(){const c=Date.now()-7*86400000;return state.sport.filter(x=>+new Date(x.createdAt)>=c).reduce((a,x)=>a+(+x.minutes||0),0)}
function avg3(k){const a=[...state.pressure].sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt)).slice(0,3);return a.length?Math.round(sum(a,k)/a.length):null}
function goalsReady(){return !!(state.goals.calories&&state.goals.sportMinutes&&state.goals.sysMax&&state.goals.diaMax)}
function guessMeal(){const h=new Date().getHours();return h<11?"Colazione":h<15?"Pranzo":h<18?"Snack":"Cena"}
function render(){ $("#todayLabel").textContent=fmtDate(new Date()).toUpperCase(); $$(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab)); $("#pageTitle").textContent=({today:"Super Me",food:"Cibo",sport:"Sport",pressure:"Pressione"})[tab]; ({today:renderToday,food:renderFood,sport:renderSport,pressure:renderPressure})[tab](); }
function renderToday(){
 const food=todayFood(),sport=todaySport(),kcal=sum(food,"kcal"),burn=sum(sport,"kcal"),bp=latest(state.pressure);
 const events=[...food.map(x=>({...x,t:"food",title:x.title,sub:`${x.meal} · ${x.kcal} kcal`})),...sport.map(x=>({...x,t:"sport",title:x.type,sub:`${x.minutes} min · ~${x.kcal} kcal`})),...state.pressure.filter(x=>isToday(x.createdAt)).map(x=>({...x,t:"pressure",title:`${x.sys}/${x.dia} mmHg`,sub:`♥ ${x.pulse||"—"} · ${x.context||"misurazione"}`}))].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));
 $("#view").innerHTML=`<div class="stack">
 ${!goalsReady()?`<div class="happy-banner"><h3>Facciamo Super Me su misura ☀️</h3><p>Imposta calorie, sport e range pressione. Ci vogliono 30 secondi.</p><button id="goalCta" class="btn btn-primary" style="margin-top:12px">Imposta obiettivi</button></div>`:""}
 <section class="card hero"><div class="row"><span class="muted small">Calorie alimentari</span><span class="badge">${state.goals.calories?`${pct(kcal,state.goals.calories)}%`:"imposta target"}</span></div><div style="margin-top:10px"><span class="kcal-number">${kcal}</span> <span class="unit">${state.goals.calories?`/ ${state.goals.calories}`:""} kcal</span></div><div class="progress"><i style="width:${pct(kcal,state.goals.calories)}%"></i></div><div class="row small"><span><b>${burn}</b> kcal sport <span class="muted">stimate</span></span><span><b>${kcal-burn}</b> bilancio semplice</span></div></section>
 <div class="grid2"><section class="card"><div class="muted small">Sport · 7 giorni</div><div class="metric" style="margin-top:6px">${weekMinutes()} <span class="small muted">min</span></div><div class="small muted">${state.goals.sportMinutes?`target ${state.goals.sportMinutes}`:"imposta target"}</div></section><section class="card"><div class="muted small">Pressione · ultima</div><div class="metric" style="margin-top:6px">${bp?`${bp.sys}/${bp.dia}`:"—"}</div><div class="small muted">${bp?`${fmtTime(bp.createdAt)} · ♥ ${bp.pulse||"—"}`:"Nessun dato"}</div></section></div>
 <div class="section-title">Aggiungi</div><div class="quick"><button data-quick="voice"><span>🎙️</span>Parla</button><button data-quick="photo"><span>📸</span>Foto</button><button data-quick="text"><span>✍️</span>Scrivi</button></div>
 <div class="section-title">Oggi</div><div class="timeline">${events.length?events.map(x=>`<div class="event"><div class="event-icon">${x.t==="food"?"🍽️":x.t==="sport"?"↗️":"♥️"}</div><div><h4>${esc(x.title)}</h4><p>${esc(x.sub)}</p></div><small class="muted">${fmtTime(x.createdAt)}</small></div>`).join(""):`<div class="empty">Niente ancora oggi.<br><span class="small">Parla, scatta o scrivi il primo dato.</span></div>`}</div>
 <div class="notice">Il bilancio semplice = calorie ingerite − calorie sportive stimate. Non rappresenta il fabbisogno energetico totale.</div></div>`;
 if($("#goalCta"))$("#goalCta").onclick=openGoals; $$("[data-quick]").forEach(b=>b.onclick=()=>openAdd(b.dataset.quick));
}
function foodCard(x){return `<div class="entry-card" data-kind="food" data-id="${x.id}"><div class="row"><div><h4>${esc(x.title)}</h4><p>${x.meal}${x.estimated?" · stima AI":""}</p><div style="margin-top:7px;display:flex;gap:5px;flex-wrap:wrap"><span class="macro-pill">P ${Math.round(x.p||0)}g</span><span class="macro-pill">C ${Math.round(x.c||0)}g</span><span class="macro-pill">G ${Math.round(x.f||0)}g</span></div></div><b>${x.kcal} kcal</b></div><button class="chip delete" style="margin-top:10px">Elimina</button></div>`}
function renderFood(){const a=todayFood(),meals=["Colazione","Pranzo","Cena","Snack"],k=sum(a,"kcal"),p=sum(a,"p"),c=sum(a,"c"),f=sum(a,"f");$("#view").innerHTML=`<div class="stack"><section class="card"><div class="row"><div><div class="muted small">Oggi</div><div class="metric">${k} <span class="small muted">kcal</span></div></div><span class="badge">${state.goals.calories?`${state.goals.calories} target`:"target?"}</span></div><div class="statrow" style="margin-top:14px"><div class="stat"><b>${Math.round(p)}g</b><small>PROTEINE</small></div><div class="stat"><b>${Math.round(c)}g</b><small>CARBO</small></div><div class="stat"><b>${Math.round(f)}g</b><small>GRASSI</small></div></div></section>${meals.map(m=>{const r=a.filter(x=>x.meal===m);return `<div><div class="meal-head"><h3>${m}</h3><span class="small muted">${sum(r,"kcal")} kcal</span></div><div class="list-group">${r.length?r.map(foodCard).join(""):`<div class="empty small">Nessuna voce</div>`}</div></div>`}).join("")}<div class="section-title">Storico</div><div class="list-group">${[...state.food].sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt)).slice(0,12).map(foodCard).join("")||`<div class="empty">Nessun pasto registrato.</div>`}</div></div>`;bindDelete()}
function renderSport(){const r=[...state.sport].sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt)),mins=weekMinutes();$("#view").innerHTML=`<div class="stack"><section class="card"><div class="row"><div><div class="muted small">Ultimi 7 giorni</div><div class="metric">${mins} <span class="small muted">min</span></div></div><span class="badge">${state.goals.sportMinutes?`${pct(mins,state.goals.sportMinutes)}%`:"target?"}</span></div><div class="progress" style="background:#eee8df"><i style="width:${pct(mins,state.goals.sportMinutes)}%;background:var(--green)"></i></div></section><div class="section-title">Attività</div><div class="list-group">${r.map(x=>`<div class="entry-card" data-kind="sport" data-id="${x.id}"><div class="row"><div><h4>${esc(x.type)}</h4><p>${x.minutes} min ${x.distance?`· ${x.distance} km`:""} ${x.elevation?`· ${x.elevation} m D+`:""} · ${x.intensity||""}</p></div><b>~${x.kcal||0} kcal</b></div><button class="chip delete" style="margin-top:10px">Elimina</button></div>`).join("")||`<div class="empty">Nessuna attività registrata.</div>`}</div></div>`;bindDelete()}
function renderPressure(){const rows=[...state.pressure].sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt)),rev=[...rows].reverse(),bp=rev[0],s3=avg3("sys"),d3=avg3("dia");$("#view").innerHTML=`<div class="stack"><section class="card"><div class="row"><div><div class="muted small">Ultima misurazione</div><div class="metric">${bp?`${bp.sys}/${bp.dia}`:"—"} <span class="small muted">mmHg</span></div><div class="small muted">${bp?`♥ ${bp.pulse||"—"} · ${esc(bp.context||"")}`:""}</div></div><div style="text-align:right"><div class="muted tiny">MEDIA ULTIME 3</div><b>${s3?`${s3}/${d3}`:"—"}</b></div></div></section><section class="card"><div class="row"><b>Andamento</b><span class="badge">ultime 12</span></div><canvas id="bpChart" class="chart" width="640" height="220"></canvas></section><div class="section-title">Storico</div><div class="list-group">${rev.slice(0,20).map(x=>`<div class="entry-card" data-kind="pressure" data-id="${x.id}"><h4>${x.sys}/${x.dia} mmHg</h4><p>${new Date(x.createdAt).toLocaleDateString("it-IT")} · ${fmtTime(x.createdAt)} · ♥ ${x.pulse||"—"} · ${esc(x.context||"")}</p><button class="chip delete" style="margin-top:10px">Elimina</button></div>`).join("")||`<div class="empty">Nessuna misurazione registrata.</div>`}</div><div class="notice">Super Me registra e visualizza i dati; non formula diagnosi e non sostituisce il parere medico.</div></div>`;drawBP(rows.slice(-12));bindDelete()}
function drawBP(rows){const c=$("#bpChart");if(!c)return;const x=c.getContext("2d"),W=c.width,H=c.height,p=32;x.clearRect(0,0,W,H);x.strokeStyle="#e9dfd3";for(let i=0;i<4;i++){let y=p+i*(H-2*p)/3;x.beginPath();x.moveTo(p,y);x.lineTo(W-p,y);x.stroke()}if(rows.length<2){x.fillStyle="#888";x.font="22px sans-serif";x.fillText("Servono almeno 2 misurazioni",p,H/2);return}const vals=rows.flatMap(r=>[r.sys,r.dia]),mn=Math.min(...vals)-10,mx=Math.max(...vals)+10,X=i=>p+i*(W-2*p)/(rows.length-1),Y=v=>H-p-(v-mn)*(H-2*p)/(mx-mn);[["sys","#b96864"],["dia","#77a4b5"]].forEach(([k,col])=>{x.strokeStyle=col;x.lineWidth=5;x.beginPath();rows.forEach((r,i)=>i?x.lineTo(X(i),Y(r[k])):x.moveTo(X(i),Y(r[k])));x.stroke();x.fillStyle=col;rows.forEach((r,i)=>{x.beginPath();x.arc(X(i),Y(r[k]),6,0,Math.PI*2);x.fill()})})}
function bindDelete(){$$(".delete").forEach(b=>b.onclick=e=>{const c=e.target.closest("[data-kind]");if(confirm("Eliminare questa voce?")){state[c.dataset.kind]=state[c.dataset.kind].filter(x=>x.id!==c.dataset.id);save()}})}
function openSheet(h){$("#sheet").innerHTML=`<div class="handle"></div>${h}`;$("#sheetBackdrop").classList.remove("hidden");$("#sheet").classList.remove("hidden")}
function closeSheet(){stopRecording(true);$("#sheetBackdrop").classList.add("hidden");$("#sheet").classList.add("hidden");$("#sheet").innerHTML=""}$("#sheetBackdrop").onclick=closeSheet;
function loadingSheet(title,text){openSheet(`<div class="sheet-head"><h2>${title}</h2><p class="muted">${text}</p></div><div class="loading"><span class="spinner"></span><b>Sto interpretando…</b></div>`)}

async function callAI(payload){
 const r=await fetch("/api/parse",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});
 const data=await r.json().catch(()=>({}));
 if(!r.ok)throw new Error(data.error||"AI non disponibile");
 return data;
}
function normaliseAI(d){
 if(!d||!d.kind)throw new Error("Risposta AI non valida");
 if(d.kind==="food")return{...d,meal:d.meal||guessMeal(),kcal:Math.round(+d.kcal||0),p:+d.p||0,c:+d.c||0,f:+d.f||0,estimated:true};
 if(d.kind==="sport"){let type=SPORT_TYPES.includes(d.type)?d.type:(String(d.type||"").toLowerCase().includes("cali")?"Calisthenics":String(d.type||"").toLowerCase().includes("corr")?"Corsa":String(d.type||"").toLowerCase().includes("cam")?"Camminata":String(d.type||"").toLowerCase().includes("calc")?"Calcio":"Bici");return{...d,type,minutes:+d.minutes||30,kcal:Math.round(+d.kcal||estimateSport(type,+d.minutes||30,d.intensity||"media"))}}
 if(d.kind==="pressure")return{...d,sys:+d.sys,dia:+d.dia,pulse:d.pulse?+d.pulse:null};
 return d;
}
function openAdd(mode=null){if(mode==="voice")return voiceFlow();if(mode==="photo")return $("#photoInput").click();if(mode==="text")return textFlow();openSheet(`<div class="sheet-head"><h2>Aggiungi</h2><p class="muted">Parla, fotografa o scrivi. Super Me prova a capire il resto.</p></div><div class="action-list"><button class="action" id="va"><span class="ico">🎙️</span><span><b>Parla</b><small>Registra una frase, poi OpenAI la trascrive e interpreta</small></span></button><button class="action" id="pa"><span class="ico">📸</span><span><b>Foto del pasto</b><small>OpenAI riconosce il cibo e stima kcal + macro</small></span></button><button class="action" id="ta"><span class="ico">✍️</span><span><b>Scrivi</b><small>Testo naturale per cibo, sport o pressione</small></span></button><button class="action" id="ma"><span class="ico">＋</span><span><b>Manuale</b><small>Inserimento senza AI</small></span></button></div>`);$("#va").onclick=voiceFlow;$("#pa").onclick=()=>$("#photoInput").click();$("#ta").onclick=textFlow;$("#ma").onclick=manualMenu}
function textFlow(prefill=""){openSheet(`<div class="sheet-head"><h2>Scrivi ✍️</h2><p class="muted">Esempio: “80 g pane, due uova e cappuccino” oppure “45 minuti di bici e 500 m D+”.</p></div><div class="field"><label>COSA VUOI REGISTRARE?</label><textarea id="natural">${esc(prefill)}</textarea></div><button class="btn btn-primary" id="parseText">Interpreta con AI</button>`);$("#parseText").onclick=async()=>{const text=$("#natural").value.trim();if(!text)return;loadingSheet("Un secondo…","Sto trasformando la frase in dati strutturati.");try{confirmParsed(normaliseAI(await callAI({text})),text)}catch(e){textFlow(text);setTimeout(()=>alert("OpenAI non è ancora disponibile: controlla OPENAI_API_KEY su Vercel. "+e.message),50)}}}
async function imageToDataUrl(file){
 const raw=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});
 const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=raw});
 const max=1100,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.round(img.width*scale),h=Math.round(img.height*scale),canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;canvas.getContext("2d").drawImage(img,0,0,w,h);return canvas.toDataURL("image/jpeg",.76)
}
$("#photoInput").addEventListener("change",async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;loadingSheet("Guardo il piatto 📸","Sto riconoscendo gli alimenti e stimando porzioni, calorie e macronutrienti.");try{const imageDataUrl=await imageToDataUrl(file);const d=normaliseAI(await callAI({imageDataUrl,text:`Analizza questo pasto. Ora locale: ${new Date().toLocaleTimeString("it-IT")}. Stima porzioni, calorie totali, proteine, carboidrati e grassi.`}));if(d.kind!=="food")d.kind="food";foodForm(d,"Analisi da foto",imageDataUrl)}catch(err){openSheet(`<div class="sheet-head"><h2>Foto acquisita</h2><p class="muted">Non sono riuscito ad analizzarla con OpenAI.</p></div><div class="notice warn">${esc(err.message)}</div><button class="btn btn-secondary" id="retryPhoto" style="margin-top:12px">Riprova con un'altra foto</button>`);$("#retryPhoto").onclick=()=>$("#photoInput").click()}});

function voiceFlow(){
 if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){openSheet(`<div class="sheet-head"><h2>Parla 🎙️</h2><p class="muted">Questo browser non espone la registrazione audio. Su Vercel/HTTPS prova Safari o Chrome aggiornato.</p></div><button class="btn btn-secondary" id="voiceFallback">Scrivi invece</button>`);$("#voiceFallback").onclick=()=>textFlow();return}
 openSheet(`<div class="sheet-head"><h2>Parla 🎙️</h2><p class="muted">Tocca il microfono, racconta cosa hai mangiato, lo sport fatto o la pressione, poi tocca di nuovo.</p></div><button class="voice-orb" id="voiceOrb">🎙️</button><div class="timer" id="timer">Tocca per iniziare</div><div class="notice">Esempio: “Ho fatto 50 minuti di bici, 20 km e 600 metri di dislivello”.</div>`);
 $("#voiceOrb").onclick=()=>mediaRecorder?.state==="recording"?stopRecording(false):startRecording();
}
function chooseMime(){const opts=["audio/webm;codecs=opus","audio/webm","audio/mp4"];return opts.find(x=>MediaRecorder.isTypeSupported?.(x))||""}
async function startRecording(){
 try{
  activeStream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];const mime=chooseMime();mediaRecorder=new MediaRecorder(activeStream,mime?{mimeType:mime}:undefined);recordStart=Date.now();
  mediaRecorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data)};
  mediaRecorder.onstop=async()=>{const blob=new Blob(recordChunks,{type:mediaRecorder.mimeType||"audio/webm"});cleanupStream();if(blob.size&&recordChunks.length)await transcribeBlob(blob)};
  mediaRecorder.start(250);$("#voiceOrb").classList.add("live","stop");$("#voiceOrb").textContent="■";updateTimer();recordTimer=setInterval(updateTimer,500);
 }catch(e){alert("Non riesco ad accedere al microfono. Controlla il permesso del browser.")}
}
function updateTimer(){const el=$("#timer");if(!el)return;const s=Math.floor((Date.now()-recordStart)/1000);el.textContent=`Registrazione ${s}s · tocca per fermare`;if(s>=45)stopRecording(false)}
function stopRecording(silent){if(recordTimer){clearInterval(recordTimer);recordTimer=null}if(mediaRecorder?.state==="recording"){mediaRecorder.stop();if(silent){mediaRecorder.onstop=()=>cleanupStream()}}else cleanupStream()}
function cleanupStream(){activeStream?.getTracks?.().forEach(t=>t.stop());activeStream=null;mediaRecorder=null}
async function blobToBase64(blob){return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(blob)})}
async function transcribeBlob(blob){
 loadingSheet("Ti ascolto…","OpenAI sta trascrivendo la registrazione.");
 try{
  const audioDataUrl=await blobToBase64(blob);
  const r=await fetch("/api/transcribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({audioDataUrl,mime:blob.type})});
  const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Trascrizione non disponibile");
  const text=(data.text||"").trim();if(!text)throw new Error("Non ho ricevuto una trascrizione");
  loadingSheet("Capito ✓",`“${esc(text)}”`);
  const parsed=normaliseAI(await callAI({text}));confirmParsed(parsed,text);
 }catch(e){openSheet(`<div class="sheet-head"><h2>Non ci sono riuscito</h2><p class="muted">Puoi riprovare oppure scrivere la frase.</p></div><div class="notice warn">${esc(e.message)}</div><button class="btn btn-primary" id="retryVoice" style="margin-top:12px">Riprova a parlare</button><button class="btn btn-secondary" id="writeInstead" style="margin-top:9px">Scrivi invece</button>`);$("#retryVoice").onclick=voiceFlow;$("#writeInstead").onclick=()=>textFlow()}
}
function confirmParsed(d,raw=""){if(d.kind==="pressure")pressureForm(d,raw);else if(d.kind==="sport")sportForm(d,raw);else foodForm(d,raw)}
function estimateSport(type,min,intensity){const w=+state.profile.weight||80,m={Bici:7.5,Corsa:8.3,Calisthenics:6,Camminata:3.5,Calcio:8};let met=m[type]||5.5;if(intensity==="alta")met*=1.2;if(intensity==="bassa")met*=.8;return Math.round(met*3.5*w/200*Math.max(min,1))}
function pressureForm(d={},raw=""){openSheet(`<div class="sheet-head"><h2>Conferma pressione</h2><p class="muted">Controlla prima di salvare.</p></div>${raw?`<div class="notice">“${esc(raw)}”</div>`:""}<div class="grid2"><div class="field"><label>SISTOLICA</label><input id="sys" type="number" value="${d.sys||""}"></div><div class="field"><label>DIASTOLICA</label><input id="dia" type="number" value="${d.dia||""}"></div></div><div class="grid2"><div class="field"><label>BATTITO</label><input id="pulse" type="number" value="${d.pulse||""}"></div><div class="field"><label>CONTESTO</label><select id="ctx">${["riposo","mattina","sera","post-caffè","post-sport","altro"].map(x=>`<option ${d.context===x?"selected":""}>${x}</option>`).join("")}</select></div></div><button class="btn btn-primary" id="saveBP">Salva misurazione</button>`);$("#saveBP").onclick=()=>{const s=+$("#sys").value,di=+$("#dia").value;if(!s||!di)return alert("Inserisci sistolica e diastolica.");state.pressure.push({id:uid(),sys:s,dia:di,pulse:+$("#pulse").value||null,context:$("#ctx").value,createdAt:nowISO()});save();closeSheet();tab="pressure";render()}}
function sportForm(d={},raw=""){openSheet(`<div class="sheet-head"><h2>Conferma sport</h2><p class="muted">Le calorie restano una stima.</p></div>${raw?`<div class="notice">“${esc(raw)}”</div>`:""}<div class="field"><label>ATTIVITÀ</label><select id="stype">${SPORT_TYPES.map(x=>`<option ${d.type===x?"selected":""}>${x}</option>`).join("")}</select></div><div class="grid2"><div class="field"><label>MINUTI</label><input id="mins" type="number" value="${d.minutes||""}"></div><div class="field"><label>INTENSITÀ</label><select id="inten">${["bassa","media","alta"].map(x=>`<option ${d.intensity===x?"selected":""}>${x}</option>`).join("")}</select></div></div><div class="grid2"><div class="field"><label>DISTANZA KM</label><input id="dist" type="number" step=".1" value="${d.distance||""}"></div><div class="field"><label>DISLIVELLO M</label><input id="elev" type="number" value="${d.elevation||""}"></div></div><div class="field"><label>CALORIE STIMATE</label><input id="skcal" type="number" value="${d.kcal||""}"></div><button class="btn btn-primary" id="saveSport">Salva attività</button>`);
 const recalc=()=>$("#skcal").value=estimateSport($("#stype").value,+$("#mins").value||30,$("#inten").value);$("#stype").onchange=recalc;$("#mins").oninput=recalc;$("#inten").onchange=recalc;
 $("#saveSport").onclick=()=>{const type=$("#stype").value,minutes=+$("#mins").value;if(!minutes)return alert("Inserisci la durata.");state.sport.push({id:uid(),type,minutes,intensity:$("#inten").value,distance:+$("#dist").value||null,elevation:+$("#elev").value||null,kcal:+$("#skcal").value||estimateSport(type,minutes,$("#inten").value),createdAt:nowISO()});save();closeSheet();tab="sport";render()}
}
function foodForm(d={},raw="",photo=null){openSheet(`<div class="sheet-head"><h2>Conferma cibo</h2><p class="muted">L'AI stima il piatto: correggi ciò che non torna.</p></div>${photo?`<img class="photo-preview" src="${photo}">`:""}${raw?`<div class="notice">“${esc(raw)}”</div>`:""}<div class="estimate"><div class="field"><label>PASTO</label><select id="meal">${["Colazione","Pranzo","Cena","Snack"].map(x=>`<option ${d.meal===x?"selected":""}>${x}</option>`).join("")}</select></div><div class="field"><label>ALIMENTI / DESCRIZIONE</label><input id="ftitle" value="${esc(d.title||"")}"></div><div class="field"><label>CALORIE</label><input id="fkcal" type="number" value="${Math.round(d.kcal||0)}"></div><div class="grid2"><div class="field"><label>PROTEINE G</label><input id="fp" type="number" step=".1" value="${d.p||0}"></div><div class="field"><label>CARBOIDRATI G</label><input id="fc" type="number" step=".1" value="${d.c||0}"></div></div><div class="field"><label>GRASSI G</label><input id="ff" type="number" step=".1" value="${d.f||0}"></div></div><div class="notice">Foto, porzioni e preparazioni possono rendere kcal e macro imprecisi: sono stime da confermare.</div><button class="btn btn-primary" id="saveFood" style="margin-top:14px">Salva pasto</button>`);$("#saveFood").onclick=()=>{const title=$("#ftitle").value.trim();if(!title)return alert("Descrivi il pasto.");state.food.push({id:uid(),meal:$("#meal").value,title,kcal:+$("#fkcal").value||0,p:+$("#fp").value||0,c:+$("#fc").value||0,f:+$("#ff").value||0,estimated:true,source:photo?"foto":"ai",createdAt:nowISO()});save();closeSheet();tab="food";render()}}
function manualMenu(){openSheet(`<div class="sheet-head"><h2>Manuale</h2><p class="muted">Inserisci senza AI.</p></div><div class="action-list"><button class="action" id="mf"><span class="ico">🍽️</span><b>Cibo</b></button><button class="action" id="ms"><span class="ico">↗️</span><b>Sport</b></button><button class="action" id="mp"><span class="ico">♥️</span><b>Pressione</b></button></div>`);$("#mf").onclick=()=>foodForm({meal:guessMeal()});$("#ms").onclick=()=>sportForm({type:"Bici",intensity:"media"});$("#mp").onclick=()=>pressureForm({context:"riposo"})}
function openGoals(){openSheet(`<div class="sheet-head"><h2>Obiettivi ☀️</h2><p class="muted">Sono i riferimenti che Super Me userà nella home.</p></div><div class="goal-card"><div class="row"><div class="goal-icon">🍽️</div><b>Cibo</b></div><div class="field"><label>CALORIE AL GIORNO</label><input id="gcal" type="number" value="${state.goals.calories||""}" placeholder="es. 2200"></div></div><div class="goal-card" style="margin-top:10px"><div class="row"><div class="goal-icon">↗️</div><b>Sport</b></div><div class="field"><label>MINUTI OGNI 7 GIORNI</label><input id="gmin" type="number" value="${state.goals.sportMinutes||""}" placeholder="es. 180"></div></div><div class="goal-card" style="margin-top:10px"><div class="row"><div class="goal-icon">♥️</div><b>Pressione</b></div><div class="grid2"><div class="field"><label>SISTOLICA MAX</label><input id="gsys" type="number" value="${state.goals.sysMax||""}" placeholder="140"></div><div class="field"><label>DIASTOLICA MAX</label><input id="gdia" type="number" value="${state.goals.diaMax||""}" placeholder="90"></div></div></div><div class="goal-card" style="margin-top:10px"><div class="row"><div class="goal-icon">⚖️</div><b>Profilo</b></div><div class="grid2"><div class="field"><label>PESO KG</label><input id="pw" type="number" step=".1" value="${state.profile.weight||""}"></div><div class="field"><label>ALTEZZA CM</label><input id="ph" type="number" value="${state.profile.height||""}"></div></div><div class="field"><label>PESO OBIETTIVO KG</label><input id="gweight" type="number" step=".1" value="${state.goals.weightTarget||""}"></div></div><button class="btn btn-primary" id="saveGoals" style="margin-top:14px">Salva obiettivi</button><button class="btn btn-danger" id="reset" style="margin-top:10px">Cancella tutti i dati locali</button>`);$("#saveGoals").onclick=()=>{state.goals.calories=+$("#gcal").value||null;state.goals.sportMinutes=+$("#gmin").value||null;state.goals.sysMax=+$("#gsys").value||null;state.goals.diaMax=+$("#gdia").value||null;state.goals.weightTarget=+$("#gweight").value||null;state.profile.weight=+$("#pw").value||null;state.profile.height=+$("#ph").value||null;save();closeSheet()};$("#reset").onclick=()=>{if(confirm("Cancellare tutti i dati salvati su questo dispositivo?")){state=defaults();localStorage.removeItem(KEY);closeSheet();render()}}}
$$("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$("#addBtn").onclick=()=>openAdd();$("#settingsBtn").onclick=openGoals;
if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
render();
})();