(() => {
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='super_me_v1',SPORTS=['Bici','Corsa','Calisthenics','Camminata','Calcio'];
const base=()=>({profile:{weight:null,height:null},goals:{calories:null,sportMinutes:null,weightTarget:null,sysMax:null,diaMax:null},food:[],sport:[],pressure:[]});
let state=(()=>{try{return {...base(),...(JSON.parse(localStorage.getItem(KEY))||{})}}catch{return base()}})(),tab='today',rec=null,chunks=[],stream=null,start=0,timer=null;
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));render()},uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2),now=()=>new Date().toISOString(),today=x=>new Date(x).toDateString()===new Date().toDateString(),sum=(a,k)=>a.reduce((s,x)=>s+(+x[k]||0),0),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const foodToday=()=>state.food.filter(x=>today(x.createdAt)),sportToday=()=>state.sport.filter(x=>today(x.createdAt)),weekMin=()=>state.sport.filter(x=>Date.now()-new Date(x.createdAt)<7*864e5).reduce((s,x)=>s+(+x.minutes||0),0),pct=(n,d)=>d?Math.min(100,Math.round(n/d*100)):0,mealNow=()=>{let h=new Date().getHours();return h<11?'Colazione':h<15?'Pranzo':h<18?'Snack':'Cena'};
function open(h){$('#sheet').innerHTML='<div class="handle"></div>'+h;$('#sheet').classList.remove('hidden');$('#sheetBackdrop').classList.remove('hidden')}function close(){stop(true);$('#sheet').classList.add('hidden');$('#sheetBackdrop').classList.add('hidden')}$('#sheetBackdrop').onclick=close;
async function ai(payload){let r=await fetch('/api/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'AI non disponibile');return d}
function render(){$('#todayLabel').textContent=new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase();$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#pageTitle').textContent={today:'Super Me',food:'Cibo',sport:'Sport',pressure:'Pressione'}[tab];({today:home,food:foodView,sport:sportView,pressure:pressureView})[tab]()}
function home(){let f=foodToday(),s=sportToday(),k=sum(f,'kcal'),b=sum(s,'kcal'),bp=[...state.pressure].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))[0];$('#view').innerHTML=`<div class="stack">${!(state.goals.calories&&state.goals.sportMinutes)?`<div class="happy-banner"><h3>Facciamo Super Me su misura ☀️</h3><p>Imposta i tuoi obiettivi una volta sola.</p><button id="goalCta" class="btn btn-primary" style="margin-top:12px">Imposta obiettivi</button></div>`:''}<section class="card hero"><div class="row"><span class="small">Calorie alimentari</span><span class="badge">${state.goals.calories?pct(k,state.goals.calories)+'%':'target?'}</span></div><div style="margin-top:10px"><span class="kcal-number">${k}</span> <span class="unit">${state.goals.calories?'/ '+state.goals.calories:''} kcal</span></div><div class="progress"><i style="width:${pct(k,state.goals.calories)}%"></i></div><div class="row small"><span>${b} kcal sport</span><span>${k-b} bilancio semplice</span></div></section><div class="grid2"><section class="card"><div class="muted small">Sport · 7 giorni</div><div class="metric">${weekMin()} <span class="small muted">min</span></div></section><section class="card"><div class="muted small">Pressione · ultima</div><div class="metric">${bp?bp.sys+'/'+bp.dia:'—'}</div><div class="small muted">${bp?'♥ '+(bp.pulse||'—'):'Nessun dato'}</div></section></div><div class="section-title">Aggiungi</div><div class="quick"><button data-q="voice"><span>🎙️</span>Parla</button><button data-q="photo"><span>📸</span>Foto</button><button data-q="text"><span>✍️</span>Scrivi</button></div><div class="notice">Il bilancio semplice non rappresenta il fabbisogno energetico totale.</div></div>`;$('#goalCta')?.addEventListener('click',goals);$$('[data-q]').forEach(b=>b.onclick=()=>add(b.dataset.q))}
function foodView(){let a=foodToday();$('#view').innerHTML=`<div class="stack"><section class="card"><div class="metric">${sum(a,'kcal')} <span class="small muted">kcal oggi</span></div><div class="statrow" style="margin-top:14px"><div class="stat"><b>${Math.round(sum(a,'p'))}g</b><small>PROTEINE</small></div><div class="stat"><b>${Math.round(sum(a,'c'))}g</b><small>CARBO</small></div><div class="stat"><b>${Math.round(sum(a,'f'))}g</b><small>GRASSI</small></div></div></section><div class="list-group">${[...state.food].reverse().map(x=>`<div class="entry-card"><div class="row"><div><h4>${esc(x.title)}</h4><p>${x.meal} · P ${Math.round(x.p)} C ${Math.round(x.c)} G ${Math.round(x.f)}</p></div><b>${x.kcal} kcal</b></div></div>`).join('')||'<div class="empty">Nessun pasto</div>'}</div></div>`}
function sportView(){let a=[...state.sport].reverse();$('#view').innerHTML=`<div class="stack"><section class="card"><div class="metric">${weekMin()} <span class="small muted">min / 7 giorni</span></div></section><div class="list-group">${a.map(x=>`<div class="entry-card"><div class="row"><div><h4>${x.type}</h4><p>${x.minutes} min ${x.distance?'· '+x.distance+' km':''} ${x.elevation?'· '+x.elevation+' m D+':''}</p></div><b>~${x.kcal} kcal</b></div></div>`).join('')||'<div class="empty">Nessuna attività</div>'}</div></div>`}
function pressureView(){let a=[...state.pressure].reverse();$('#view').innerHTML=`<div class="stack">${a.map(x=>`<div class="entry-card"><h4>${x.sys}/${x.dia} mmHg</h4><p>♥ ${x.pulse||'—'} · ${esc(x.context||'riposo')}</p></div>`).join('')||'<div class="empty">Nessuna misurazione</div>'}<div class="notice">Super Me registra e visualizza i dati; non formula diagnosi.</div></div>`}
function add(mode){if(mode==='voice')return voice();if(mode==='photo')return $('#photoInput').click();if(mode==='text')return text();open(`<div class="sheet-head"><h2>Aggiungi</h2><p class="muted">Racconta cosa hai fatto.</p></div><div class="action-list"><button class="action" id="v"><span class="ico">🎙️</span><span><b>Parla</b><small>Voce → trascrizione → dati</small></span></button><button class="action" id="p"><span class="ico">📸</span><span><b>Foto del pasto</b><small>Foto → kcal e macro</small></span></button><button class="action" id="t"><span class="ico">✍️</span><span><b>Scrivi</b><small>Testo naturale</small></span></button><button class="action" id="m"><span class="ico">＋</span><span><b>Manuale</b></span></button></div>`);$('#v').onclick=voice;$('#p').onclick=()=>$('#photoInput').click();$('#t').onclick=text;$('#m').onclick=manual}
function text(prefill=''){open(`<div class="sheet-head"><h2>Scrivi ✍️</h2><p class="muted">Cibo, sport o pressione.</p></div><div class="field"><label>TESTO</label><textarea id="txt">${esc(prefill)}</textarea></div><button class="btn btn-primary" id="go">Interpreta con AI</button>`);$('#go').onclick=async()=>{let t=$('#txt').value.trim();if(!t)return;try{confirm(await ai({text:t}),t)}catch(e){alert(e.message)}}}
function confirm(d,raw=''){if(d.kind==='food')return foodForm(d,raw);if(d.kind==='sport')return sportForm(d,raw);return bpForm(d,raw)}
function foodForm(d={},raw=''){open(`<div class="sheet-head"><h2>Conferma cibo</h2><p class="muted">Controlla la stima AI.</p></div>${raw?`<div class="notice">“${esc(raw)}”</div>`:''}<div class="field"><label>PASTO</label><select id="meal">${['Colazione','Pranzo','Cena','Snack'].map(x=>`<option ${d.meal===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>DESCRIZIONE</label><input id="title" value="${esc(d.title||'')}"></div><div class="field"><label>CALORIE</label><input id="k" type="number" value="${Math.round(d.kcal||0)}"></div><div class="grid2"><div class="field"><label>PROTEINE G</label><input id="p" type="number" value="${d.p||0}"></div><div class="field"><label>CARBO G</label><input id="c" type="number" value="${d.c||0}"></div></div><div class="field"><label>GRASSI G</label><input id="f" type="number" value="${d.f||0}"></div><button class="btn btn-primary" id="saveF">Salva</button>`);$('#saveF').onclick=()=>{state.food.push({id:uid(),meal:$('#meal').value,title:$('#title').value,kcal:+$('#k').value||0,p:+$('#p').value||0,c:+$('#c').value||0,f:+$('#f').value||0,createdAt:now(),estimated:true});save();close();tab='food';render()}}
function sportForm(d={}){let type=SPORTS.includes(d.type)?d.type:'Bici';open(`<div class="sheet-head"><h2>Conferma sport</h2></div><div class="field"><label>ATTIVITÀ</label><select id="st">${SPORTS.map(x=>`<option ${x===type?'selected':''}>${x}</option>`).join('')}</select></div><div class="grid2"><div class="field"><label>MINUTI</label><input id="min" type="number" value="${d.minutes||30}"></div><div class="field"><label>CALORIE</label><input id="sk" type="number" value="${Math.round(d.kcal||0)}"></div></div><div class="grid2"><div class="field"><label>KM</label><input id="dist" type="number" step=".1" value="${d.distance||''}"></div><div class="field"><label>D+ M</label><input id="elev" type="number" value="${d.elevation||''}"></div></div><button class="btn btn-primary" id="saveS">Salva</button>`);$('#saveS').onclick=()=>{state.sport.push({id:uid(),type:$('#st').value,minutes:+$('#min').value||0,kcal:+$('#sk').value||0,distance:+$('#dist').value||null,elevation:+$('#elev').value||null,createdAt:now()});save();close();tab='sport';render()}}
function bpForm(d={}){open(`<div class="sheet-head"><h2>Conferma pressione</h2></div><div class="grid2"><div class="field"><label>SISTOLICA</label><input id="sys" type="number" value="${d.sys||''}"></div><div class="field"><label>DIASTOLICA</label><input id="dia" type="number" value="${d.dia||''}"></div></div><div class="field"><label>BATTITO</label><input id="pulse" type="number" value="${d.pulse||''}"></div><button class="btn btn-primary" id="saveB">Salva</button>`);$('#saveB').onclick=()=>{state.pressure.push({id:uid(),sys:+$('#sys').value,dia:+$('#dia').value,pulse:+$('#pulse').value||null,context:d.context||'riposo',createdAt:now()});save();close();tab='pressure';render()}}
function manual(){open(`<div class="sheet-head"><h2>Manuale</h2></div><div class="action-list"><button class="action" id="mf"><b>Cibo</b></button><button class="action" id="ms"><b>Sport</b></button><button class="action" id="mb"><b>Pressione</b></button></div>`);$('#mf').onclick=()=>foodForm({meal:mealNow()});$('#ms').onclick=()=>sportForm({type:'Bici'});$('#mb').onclick=()=>bpForm({})}
function goals(){open(`<div class="sheet-head"><h2>Obiettivi ☀️</h2></div><div class="field"><label>CALORIE / GIORNO</label><input id="gc" type="number" value="${state.goals.calories||''}"></div><div class="field"><label>SPORT MIN / 7 GIORNI</label><input id="gm" type="number" value="${state.goals.sportMinutes||''}"></div><div class="grid2"><div class="field"><label>PESO KG</label><input id="gw" type="number" step=".1" value="${state.profile.weight||''}"></div><div class="field"><label>PESO TARGET</label><input id="gt" type="number" step=".1" value="${state.goals.weightTarget||''}"></div></div><div class="grid2"><div class="field"><label>SISTOLICA MAX</label><input id="gs" type="number" value="${state.goals.sysMax||''}"></div><div class="field"><label>DIASTOLICA MAX</label><input id="gd" type="number" value="${state.goals.diaMax||''}"></div></div><button class="btn btn-primary" id="saveG">Salva obiettivi</button>`);$('#saveG').onclick=()=>{state.goals.calories=+$('#gc').value||null;state.goals.sportMinutes=+$('#gm').value||null;state.goals.weightTarget=+$('#gt').value||null;state.goals.sysMax=+$('#gs').value||null;state.goals.diaMax=+$('#gd').value||null;state.profile.weight=+$('#gw').value||null;save();close()}}
async function imageData(file){let raw=await new Promise((r,j)=>{let f=new FileReader();f.onload=()=>r(f.result);f.onerror=j;f.readAsDataURL(file)}),img=await new Promise((r,j)=>{let i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=raw}),scale=Math.min(1,1100/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=img.width*scale;c.height=img.height*scale;c.getContext('2d').drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.76)}
$('#photoInput').onchange=async e=>{let f=e.target.files?.[0];e.target.value='';if(!f)return;try{open('<div class="loading"><span class="spinner"></span><b>Analizzo il piatto…</b></div>');let imageDataUrl=await imageData(f),d=await ai({imageDataUrl,text:'Analizza il pasto, stima porzioni, calorie e macronutrienti.'});foodForm(d,'Analisi da foto')}catch(err){alert(err.message);close()}};
async function voice(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return alert('Browser non compatibile con la registrazione audio.');open(`<div class="sheet-head"><h2>Parla 🎙️</h2><p class="muted">Tocca per iniziare, poi di nuovo per fermare.</p></div><button class="voice-orb" id="orb">🎙️</button><div class="timer" id="tm">Tocca per iniziare</div>`);$('#orb').onclick=()=>rec?.state==='recording'?stop(false):startRec()}
async function startRec(){try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];let mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(x=>MediaRecorder.isTypeSupported?.(x))||'';rec=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=async()=>{let blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'});cleanup();await transcribe(blob)};rec.start(250);start=Date.now();$('#orb').textContent='■';$('#orb').classList.add('live','stop');timer=setInterval(()=>{$('#tm').textContent='Registrazione '+Math.floor((Date.now()-start)/1000)+'s · tocca per fermare'},500)}catch(e){alert('Permesso microfono non disponibile')}}
function stop(silent){if(timer)clearInterval(timer),timer=null;if(rec?.state==='recording'){if(silent)rec.onstop=cleanup;rec.stop()}else cleanup()}function cleanup(){stream?.getTracks?.().forEach(t=>t.stop());stream=null;rec=null}
async function transcribe(blob){try{open('<div class="loading"><span class="spinner"></span><b>Trascrivo…</b></div>');let audioDataUrl=await new Promise((r,j)=>{let f=new FileReader();f.onload=()=>r(f.result);f.onerror=j;f.readAsDataURL(blob)}),rr=await fetch('/api/transcribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({audioDataUrl})}),d=await rr.json();if(!rr.ok)throw Error(d.error||'Errore trascrizione');let parsed=await ai({text:d.text});confirm(parsed,d.text)}catch(e){alert(e.message);close()}}
$$('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$('#addBtn').onclick=()=>add();$('#settingsBtn').onclick=goals;if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});render();
})();
