const json = (res, status, data) => res.status(status).json(data);
function decodeDataUrl(dataUrl){if(typeof dataUrl!=="string"||!dataUrl.startsWith("data:"))throw new Error("Audio non valido");const comma=dataUrl.indexOf(",");if(comma===-1)throw new Error("Audio non valido");const meta=dataUrl.slice(5,comma),payload=dataUrl.slice(comma+1),parts=meta.split(";").filter(Boolean),mime=parts[0]||"audio/webm",isBase64=parts.includes("base64"),buffer=Buffer.from(payload,isBase64?"base64":"utf8");if(!buffer.length)throw new Error("Audio vuoto");return{mime,buffer}}
function extensionFor(mime){const m=String(mime||"").toLowerCase();if(m.includes("mp4")||m.includes("m4a"))return"m4a";if(m.includes("ogg"))return"ogg";if(m.includes("wav"))return"wav";if(m.includes("mpeg")||m.includes("mp3"))return"mp3";return"webm"}
export default async function handler(req,res){
 if(req.method!=="POST")return json(res,405,{error:"Method not allowed"});const key=process.env.OPENAI_API_KEY;if(!key)return json(res,503,{error:"OPENAI_API_KEY non configurata su Vercel"});
 try{const{audioDataUrl}=req.body||{}, {mime,buffer}=decodeDataUrl(audioDataUrl);if(buffer.length>8_000_000)return json(res,413,{error:"Registrazione troppo lunga. Prova con una frase più breve."});
 const form=new FormData();form.append("file",new Blob([buffer],{type:mime}),`recording.${extensionFor(mime)}`);form.append("model","gpt-4o-mini-transcribe");form.append("language","it");form.append("prompt","Trascrivi fedelmente italiano per l'app Super Me. Termini possibili: peso, chilogrammi, kg, pressione, sistolica, diastolica, battito, caffè, espresso, meditazione, meditato, minuti, calorie, proteine, carboidrati, grassi, sodio, sale, grammi, bici, MTB, corsa, calisthenics, calistenics, camminata, calcio, dislivello, libro, autore, fumato, sigaretta.");
 const response=await fetch("https://api.openai.com/v1/audio/transcriptions",{method:"POST",headers:{Authorization:`Bearer ${key}`},body:form});const data=await response.json().catch(()=>({}));if(!response.ok)return json(res,response.status,{error:data?.error?.message||`Errore trascrizione OpenAI (${response.status})`});return json(res,200,{text:String(data.text||"").trim()});
 }catch(error){console.error("Transcription internal error",{message:error?.message});return json(res,500,{error:error?.message||"Errore interno nella trascrizione"});}
}
